{% set name = "hdbpp-es" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/hdbpp/hdbpp-es/-/archive/{{ version }}/hdbpp-es-{{ version }}.tar.gz
  sha256: 75f5ef639c840c76a098368198184bb06697b2fe232c2c0d5483dfc611e764de

build:
  number: 1
  skip: true  # [not linux]
  # Prevent hdb++es-srv.dbg to be modified
  binary_relocation:
    - bin/hdb++es-srv

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango <9.4
    - omniorb
    - omniorb-libs
    - libhdbpp >=2.1.0

test:
  commands:
    - hdb++es-srv --help 2>&1 | grep usage

outputs:
  - name: hdbpp-es
    files:
      - bin/hdb++es-srv

  - name: hdbpp-es-dbg
    requirements:
      run:
        - {{ pin_subpackage('hdbpp-es', exact=True) }}
    files:
      - bin/hdb++es-srv.dbg
    test:
      commands:
        - test -f ${PREFIX}/bin/hdb++es-srv.dbg

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango device server for the HDB++ Event Subscriber
  dev_url: https://gitlab.com/tango-controls/hdbpp/hdbpp-es
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/archiving/HDB++.html

extra:
  recipe-maintainers:
    - beenje
